/**
 * Example Service API Spec
 * No description available
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */

import { PocketCurrency } from './pocketCurrency';


export interface PocketPostRequestBody { 
    ["name"]: string;
    ["goal"]?: PocketCurrency;
    ["arrangementId"]?: string;
    ["fundAmount"]?: PocketCurrency;
}

