/**
 * Example Service API Spec
 * No description available
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */

import { PocketTransaction } from './pocketTransaction';
import { PocketCurrency } from './pocketCurrency';


export interface Pocket { 
    ["id"]: string;
    ["name"]: string;
    ["funds"]?: PocketCurrency;
    ["goal"]?: PocketCurrency;
    ["goalDate"]?: string;
    ["transactions"]?: Array<PocketTransaction>;
}

